import { useMemo, useState } from 'react'
import './App.css'
import {
  ACTUAL_EVENTS, ANCHORS, ARCHITECTURES, ARCH_IDS, DATES, SNAPSHOTS, STEPS,
  actualAt, availablePlans, compareBranches, eventsUntil, fitness, knownRequirements,
  planKnowledge, routeApplicability, selectedPlan,
  type ArchitectureId, type ArchitectureSnapshot, type Condition, type PlanRevision,
} from './model'

type Stage = 'A' | 'B' | 'C'
const lensText: Record<Stage,{title:string;blurb:string}> = {
 A: {title:'План и условные Evolution Steps',blurb:'Разделены фактическое состояние, запланированные архитектурные состояния и условия применимости маршрутов.'},
 B: {title:'Календарь, прогнозы и ревизии',blurb:'На общей дате видно локальное фактическое состояние каждой архитектуры. Исторические планы не переписываются.'},
 C: {title:'Миграции и Evolution Fitness',blurb:'Сравнивайте цену необходимых миграций и соответствие известному плану — без скрытого числа или победителя.'},
}
const formatDate=(date:string)=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(`${date}T12:00:00`))
function Pill({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'blue'|'amber'|'green'|'red'}){return <span className={`pill ${tone}`}>{children}</span>}
function ArchitectureCard({snapshot,label}:{snapshot:ArchitectureSnapshot;label:string}){
 return <section className="surface architecture-card"><div className="surface-title"><div><span className="label">{label}</span><h3>{snapshot.title}</h3></div><Pill tone="blue">{snapshot.id}</Pill></div><div className="module-grid">{snapshot.modules.map(m=><div className="module" key={m.id}><div className="module-name"><span className="dot"/>{m.name}</div><p>{m.responsibility}</p><small>{m.files.join(' · ')}</small></div>)}</div><div className="arrows"><strong>Связи:</strong> {snapshot.connections.join('  /  ')}</div></section>
}
function CurrentStrip({a,date}:{a:ArchitectureId;date:string}){const e=actualAt(a,date);const req=knownRequirements(a,date);return <div className="current-strip"><div><span className="label">ФАКТИЧЕСКИЙ CURRENT</span><strong>{e.label}</strong><small>{e.id} · {formatDate(e.date)} · code: {e.codeRef}</small></div><div className="number-block"><strong>{req.length}</strong><span>известных требований</span></div></div>}
function PlanHeader({plan}:{plan:PlanRevision}){const known=planKnowledge(plan);return <section className="surface plan-header"><div className="surface-title"><div><span className="label">НЕИЗМЕНЯЕМАЯ РЕВИЗИЯ ПЛАНА</span><h3>{plan.id} <small className="subheading">создан {formatDate(plan.created)}</small></h3></div><Pill tone="blue">BASE: {plan.baseEventId}</Pill></div><p>{plan.note}</p><div className="metrics"><div><span>Требования, известные на BASE</span><strong>{known.map(x=>x.id).join(', ')}</strong></div><div><span>Прогноз готовности</span><strong>{formatDate(plan.forecastCompletion)}</strong></div><div><span>Общее окно клиента</span><strong>{formatDate(plan.externalDeadline)}</strong></div><div><span>Дедлайн интеграции</span><strong>{formatDate(plan.integrationDeadline)}</strong></div></div></section>}
function StageA({architecture,date,plan,route,onRouteChange,selectedStepRef,onStepChange}:{architecture:ArchitectureId;date:string;plan:PlanRevision;route:Condition;onRouteChange:(value:Condition)=>void;selectedStepRef:string;onStepChange:(value:string)=>void}){
 const possible=plan.routes.find(r=>r.id===route)!
 const stepRefs=[...plan.commonSteps,...possible.steps]
 const chosen=STEPS[stepRefs.includes(selectedStepRef)?selectedStepRef:stepRefs[0]]
 const status=routeApplicability(architecture,date,route)
 const target=SNAPSHOTS[chosen.target]
 const current=SNAPSHOTS[actualAt(architecture,date).architectureRef]
 return <>
  <PlanHeader plan={plan}/>
  <div className="two-column"><section className="surface"><div className="surface-title"><div><span className="label">УСЛОВНЫЕ МАРШРУТЫ ВНУТРИ PLAN</span><h3>Один Plan, два возможных будущих пути</h3></div></div><div className="route-switch">{plan.routes.map(r=><button type="button" key={r.id} className={route===r.id?'selected':''} onClick={()=>onRouteChange(r.id)}>{r.label}</button>)}</div><div className="route-info"><Pill tone={status==='applicable'?'green':status==='excluded'?'red':'amber'}>{status==='applicable'?'Условие наступило':status==='excluded'?'Не произошло в этой истории':'Будущее ещё не определено'}</Pill><span>{possible.condition}</span></div><div className="flow"><div className="flow-start">BASE · {plan.baseEventId}</div>{stepRefs.map((ref,index)=>{const step=STEPS[ref];const isOptional=index>=plan.commonSteps.length;return <button key={ref} type="button" onClick={()=>onStepChange(ref)} className={`step ${chosen.ref===ref?'active':''}`}><span className="step-num">{isOptional?'IF':String(index+1).padStart(2,'0')}</span><span><strong>{step.title}</strong><small>{step.ref} · {formatDate(step.date)} · {step.kind}</small></span><span className="step-arrow">↗</span></button>})}</div><div className="outside-work"><strong>В Plan, но не Evolution Steps</strong>{plan.otherActivities.map(s=><span key={s}>{s}</span>)}</div></section>
  <section className="surface step-detail"><span className="label">ВЫБРАННЫЙ ЗАПЛАНИРОВАННЫЙ STEP</span><h3>{chosen.title}</h3><div className="pills"><Pill tone="blue">{chosen.ref}</Pill><Pill>{chosen.kind}</Pill>{chosen.revisedFrom&&<Pill tone="amber">REVISED_FROM {chosen.revisedFrom}</Pill>}</div><p className="lead">{chosen.effect}</p><h4>Изменяемая реализация</h4><div className="file-stack">{chosen.files.map(f=><code key={f}>{f}</code>)}</div><h4>Работы, нужные для Step</h4><div className="chip-wrap">{chosen.plannedWork.map(w=><span key={w} className="chip">{w}</span>)}</div><div className="mini-note"><strong>Плановое ≠ фактическое</strong><p>Выбор Step показывает его предполагаемый результат, но не перемещает фактический курсор и не означает исполнения.</p></div></section></div>
 <div className="snapshots"><ArchitectureCard snapshot={current} label="ACTUAL · по выбранной дате"/><ArchitectureCard snapshot={target} label={`PLANNED · после ${chosen.ref}`}/></div><div className="identity-note">{current.id===target.id?'Архитектурные снимки совпадают. Это допустимо: функциональность/код в Step при этом могут измениться.':'Архитектурная структура отличается, но выбранное плановое состояние не является уже реализованным.'}</div>
 </>
}
function StageB({architecture,date,plan}:{architecture:ArchitectureId;date:string;plan?:PlanRevision}){
 const events=eventsUntil(architecture,date);const current=actualAt(architecture,date)
 const plans=availablePlans(architecture,date)
 const other=architecture==='policy'?'handler':'policy'
 const otherEvent=actualAt(other,date)
 return <><section className="surface"><div className="surface-title"><div><span className="label">ОБЩИЕ НЕЗАВИСИМЫЕ ОБСТОЯТЕЛЬСТВА</span><h3>Один календарь · разные фактические истории</h3></div><Pill tone="blue">{formatDate(date)}</Pill></div><div className="anchor-grid">{ANCHORS.map(anchor=><div key={anchor.id} className={`anchor ${date>=anchor.date?'passed':''}`}><span className="label">{formatDate(anchor.date)}</span><strong>{anchor.label}</strong><p>{anchor.explanation}</p></div>)}</div><div className="compare-cursors"><div><strong>{ARCHITECTURES[architecture].label}</strong><span>{current.id} · {current.label}</span></div><div><strong>{ARCHITECTURES[other].label}</strong><span>{otherEvent.id} · {otherEvent.label}</span></div></div></section>
 <div className="two-column"><section className="surface"><div className="surface-title"><div><span className="label">ACTUAL EVENT HISTORY</span><h3>Факты и последствия ветки</h3></div><Pill tone="green">{events.length} событий</Pill></div><div className="event-stream">{events.map(event=><div className="event" key={event.id}><span className="event-date">{formatDate(event.date)}</span><div><div><strong>{event.label}</strong><code>{event.id}</code></div>{event.sharedAnchor&&<small>Общее внешнее событие: {event.sharedAnchor}</small>}{event.planCreated&&<small>Создана ревизия {event.planCreated}</small>}{event.reason&&<p>{event.reason}</p>}{event.requirementAdded&&<Pill tone="green">Фактическое новое требование: {event.requirementAdded}</Pill>}</div></div>)}</div></section>
 <section className="surface"><div className="surface-title"><div><span className="label">СОСТОЯНИЕ ЗНАНИЯ</span><h3>Прогноз не создаёт факт</h3></div></div><h4>Фактически известные требования сейчас</h4>{knownRequirements(architecture,date).map(req=><div className="demand" key={req.id}><strong>{req.id} · {req.title}</strong><p>{req.detail}</p></div>)}{plan&&<><h4>Предсказано командой в {plan.id}</h4>{plan.anticipated.map(a=><div className="forecast" key={a.id}><strong>{a.label}</strong><p>{a.effect}</p>{a.predictedRequirementId&&<small>Ожидаемое, но не фактическое: {a.predictedRequirementId}</small>}</div>)}<h4>Change Axes · прогноз на момент ревизии</h4>{plan.axes.map(axis=><div className="axis" key={axis.name}><div><strong>{axis.name}</strong><Pill tone={axis.salience==='high'?'amber':'blue'}>{axis.salience}</Pill></div><p>{axis.outlook}</p></div>)}<h4>Ожидаемое направление маршрутов</h4><p>{plan.expectation}</p></> }</section></div>
 <section className="surface"><div className="surface-title"><div><span className="label">ПЛАНОВАЯ ИСТОРИЯ</span><h3>Ревизии доступны без переписывания прошлого</h3></div></div><div className="revision-grid">{plans.map(p=><div key={p.id} className="revision-card"><strong>{p.id}</strong><small>{formatDate(p.created)} · BASE {p.baseEventId}</small><p>{p.note}</p><span>Прогноз: {formatDate(p.forecastCompletion)} · фиксированный внешний дедлайн: {formatDate(p.externalDeadline)}</span><span>Интеграционный срок: {formatDate(p.integrationDeadline)}</span><span>Change Axis «Интеграции»: {p.axes[1].salience}</span>{p.from&&<code>REVISED_FROM {p.from}</code>}</div>)}</div></section>
 </>
}
function StageC({architecture,date,plan,route,onRouteChange}:{architecture:ArchitectureId;date:string;plan:PlanRevision;route:Condition;onRouteChange:(route:Condition)=>void}){
 const evidence=fitness(architecture,route);const alternative=fitness(architecture,route==='contract_signed'?'contract_lost':'contract_signed');const routeRecord=plan.routes.find(r=>r.id===route)!
 return <><section className="surface"><div className="surface-title"><div><span className="label">EVOLUTION FITNESS · БЕЗ ЕДИНОГО БАЛЛА</span><h3>Относительно плана, состояния и возможного будущего</h3></div><Pill tone="blue">{plan.id}</Pill></div><div className="route-switch">{plan.routes.map(r=><button key={r.id} type="button" className={r.id===route?'selected':''} onClick={()=>onRouteChange(r.id)}>{r.label}</button>)}</div><div className="fitness-grid"><div className="fitness-focus"><span className="label">01 · ВЫНУЖДЕННЫЕ / НЕУДОБНЫЕ МИГРАЦИИ</span><h3>Что потребуется изменить до реализации?</h3><p>{evidence.migration}</p></div><div className="fitness-focus"><span className="label">02 · СОГЛАСОВАННОСТЬ С ПЛАНОМ</span><h3>Укладывается ли действие в будущие Steps?</h3><p>{evidence.alignment}</p></div></div><div className="work-evidence"><div><span className="label">ОБЪЯСНИМАЯ РАБОТА</span><h3>Какие изменения и затраты за этим стоят</h3></div><div className="chip-wrap">{evidence.work.map(x=><span className="chip" key={x}>{x}</span>)}</div><div className="mini-note"><strong>Компромисс</strong><p>{evidence.caution}</p></div></div></section>
 <div className="two-column"><section className="surface"><span className="label">ВЫБРАННЫЙ МАРШРУТ</span><h3>{routeRecord.label}</h3><p>{routeRecord.condition}</p><p>На {formatDate(date)}: <strong>{routeApplicability(architecture,date,route)==='applicable'?'условие наступило':routeApplicability(architecture,date,route)==='excluded'?'исключён фактической историей':'ещё неизвестно'}</strong>. Это ничего не говорит о выполнении Steps.</p><div className="chip-wrap">{routeRecord.steps.map(ref=><span key={ref} className="chip">{ref}</span>)}</div></section><section className="surface"><span className="label">КОНТРАФАКТУАЛЬНАЯ АЛЬТЕРНАТИВА ТОГО ЖЕ ПЛАНА</span><h3>{plan.routes.find(r=>r.id!==route)?.label}</h3><p><strong>Миграции:</strong> {alternative.migration}</p><p><strong>Согласованность:</strong> {alternative.alignment}</p><div className="mini-note">Не суммируем взаимоисключающие ветки и не объявляем победителя автоматически.</div></section></div>
 <section className="surface"><div className="surface-title"><div><span className="label">SCENARIO AUTHORSHIP EVIDENCE</span><h3>Причины заданных событий — часть сценария, не вычисление движка</h3></div></div><div className="cause-lines">{ACTUAL_EVENTS[architecture].filter(e=>e.reason).map(e=><p key={e.id}><strong>{e.id}</strong> {e.reason}</p>)}</div></section>
 </>
}
export default function App(){
 const [architecture,setArchitecture]=useState<ArchitectureId>('policy')
 const [date,setDate]=useState<string>('2026-04-02')
 const [stage,setStage]=useState<Stage>('A')
 const [planId,setPlanId]=useState('A-R2')
 const [route,setRoute]=useState<Condition>('contract_signed')
 const [selectedStepRef,setSelectedStepRef]=useState('A-S3@v1')
 const plan=selectedPlan(architecture,date,planId)
 const comparison=useMemo(()=>compareBranches(date),[date])
 const plans=availablePlans(architecture,date)
 const chooseArchitecture=(id:ArchitectureId)=>{setArchitecture(id);setPlanId('');setSelectedStepRef('')}
 return <div className="app-shell"><header className="hero"><div className="hero-main"><div className="project-mark">AES <span>LAB · 005</span></div><div><span className="label light">DETERMINISTIC SEMANTIC PROTOTYPE</span><h1>Architecture Evolution <em>Simulator</em></h1><p>Один Plan · условные Evolution Steps · честные факты · объяснимые компромиссы</p></div></div><div className="hero-status"><div className="signal"/><div><strong>Prototype PT-005</strong><span>Stage A/B/C · candidate · не semantic commit</span></div></div></header>
 <div className="workspace"><aside className="sidebar"><div className="sidebar-label">01 / АРХИТЕКТУРА</div><div className="architecture-choices">{ARCH_IDS.map(id=><button className={architecture===id?'on':''} key={id} type="button" onClick={()=>chooseArchitecture(id)}><span>{ARCHITECTURES[id].label}</span><small>{ARCHITECTURES[id].strategy}</small></button>)}</div><div className="sidebar-label">02 / ОБЩИЙ КАЛЕНДАРЬ</div><div className="date-list">{DATES.map(d=><button type="button" className={date===d?'on':''} key={d} onClick={()=>{setDate(d);setPlanId('')}}>{formatDate(d)}</button>)}</div><CurrentStrip a={architecture} date={date}/><div className="sidebar-label">03 / РЕВИЗИЯ PLAN</div><select className="plan-select" value={plan?.id??''} onChange={e=>{setPlanId(e.target.value);setSelectedStepRef('')}} disabled={!plans.length}>{plans.length?plans.map(p=><option key={p.id} value={p.id}>{p.id} · {formatDate(p.created)}</option>):<option value="">План ещё не создан</option>}</select><div className="sidebar-hint">Выбирай старую ревизию для проверки no-hindsight. Actual CURRENT не изменится.</div><div className="comparison"><span className="sidebar-label">НА ЭТУ ЖЕ ДАТУ</span>{comparison.map(c=><div key={c.architecture}><strong>{ARCHITECTURES[c.architecture].label}</strong><small>{c.current.id} · {c.requirements.length} факт. требований</small></div>)}</div></aside>
 <main className="main"><div className="main-heading"><div><span className="label">ИНТЕРАКТИВНОЕ ИССЛЕДОВАНИЕ</span><h2>{lensText[stage].title}</h2><p>{lensText[stage].blurb}</p></div><div className="stage-switch">{(['A','B','C'] as Stage[]).map(s=><button type="button" className={stage===s?'on':''} key={s} onClick={()=>setStage(s)}>Stage {s}</button>)}</div></div>
 {plan?stage==='A'?<StageA architecture={architecture} date={date} plan={plan} route={route} onRouteChange={r=>{setRoute(r);setSelectedStepRef('')}} selectedStepRef={selectedStepRef} onStepChange={setSelectedStepRef}/>:stage==='B'?<StageB architecture={architecture} date={date} plan={plan}/>:<StageC architecture={architecture} date={date} plan={plan} route={route} onRouteChange={setRoute}/>:<section className="surface empty"><h3>На эту дату Plan ещё не создан</h3><p>Внешний мир и фактическая история уже существуют. Выбери 3 марта или более позднюю дату, чтобы исследовать план; Stage B всё равно показывает историю.</p>{stage==='B'&&<StageB architecture={architecture} date={date}/>}</section>}
 <footer><span>PT-005 · фикциональный сценарий без генерации будущих событий</span><span>План ≠ факт · условие ≠ выполнение · прогноз ≠ требование</span></footer></main></div></div>
}
